### ISSUE TITLE
<html> tag & text/plain missing

### ISSUE THREAD

**Issue by francoisjacquet** [getgrav/grav-plugin-email#119]
Hello,

Thank you for this great plugin.

The message sent by the plugin is HTML-only, but there is no HTML / `<html>` tag: https://wiki.apache.org/spamassassin/Rules/HTML_MIME_NO_HTML_TAG

Also, a text version of your message (`text/plain`) should also be included: https://wiki.apache.org/spamassassin/Rules/MIME_HTML_ONLY

Those 2 errors raise SpamAssassin score to -1.7 (-5 is considered spam).

Is there anything we can do about it?

**Comment by rhukster** [comment]
Please try with Email 4.0 as this now uses Symfony/Mailer (https://getgrav.org/blog/new-email-plugin)
