### ISSUE TITLE
404 error after update from GRAV 1.6.9 to 1.7.0 beta 4

### ISSUE THREAD

**Issue by withindale** [getgrav/grav-plugin-email#120]

**Comment by withindale** [comment]
After upgrading from GRAV 1.6.9 to 1.7.0 beta 4 an 400 error appears after pressing Send on a contact form. The same form copied to a 1.6.9 site works as before.

Mail Engine: SMTP
Content: HTML
Pathe to send mail: /usr/sbin/sendmail
Server: Litespeed (404 page generated by Litespeed)

**Comment by mahagr** [comment]
There was a bug which will be fixed for the next version (with Gantry at least):
https://github.com/getgrav/grav-plugin-form/issues/355

**Comment by NicoHood** [comment]
This is fixed now, right?
