### ISSUE TITLE
Issue with Emailvalidator

### ISSUE THREAD

**Issue by TrayserCassa** [getgrav/grav-plugin-email#125]
Currently I have an Issue with the email Plugin. When sending the email I got an error which is described here:

https://github.com/egulias/EmailValidator/issues/212

Maybe you can update the Validator so I can update your plugin for fixing this issue?

**Comment by rhukster** [comment]
That is the email address that you are having trouble validating?

**Comment by TrayserCassa** [comment]
it is a Nullreferenz exception in EmailValidator. 

Ok nevermind. I checked it on my server and it worked.. only on localhost it is not possible..
