### ISSUE TITLE
Showing some error after submitting form

### ISSUE THREAD

**Issue by geogeorgejoseph** [getgrav/grav-plugin-email#126]
Showing some error after submitting form

**"Class Swift_Transport_Esmtp_Auth_LoginAuthenticator does not exist"**

![Crikey  There was an error   ](https://user-images.githubusercontent.com/25584016/72223631-00ebab00-3597-11ea-8c89-a8ee168e3a90.png)

**Comment by rhukster** [comment]
This appears like your installation of Emaiil was not complete, ie, some files are missing.  We're actually moving away from Switmailer in favor of Symfony/Mailer.  Please test with this (https://getgrav.org/blog/new-email-plugin).
