### ISSUE TITLE
Contact form uses 'from' address instead of 'to' address

### ISSUE THREAD

**Issue by makruiten** [getgrav/grav-plugin-email#13]
The contact form extracts the 'from' address from the Email plugin, which of course should be the 'to' address. This is in 01.home/modular.md.

**Comment by flaviocopes** [comment]
You can change that to any address you want. 
Is that a skeleton you are using? That is just an example in your skeleton, not in the Email plugin. You can suggest an edit to that skeleton if you want.

**Comment by makruiten** [comment]
Sorry, I'm opening issues on the wrong github!
