### ISSUE TITLE
File attachment not showing in mail and also i put validation file are valid but email not set that showing error. 

### ISSUE THREAD

**Issue by amicasepoint** [getgrav/grav-plugin-email#131]
name: career-form
    class: abc
    fields:
        -
            name: fullname
            label: 'Full Name'
            type: text
            autofocus: 'off'
            validate: null
        -
            name: emails
            label: Email
            type: email
            validate: null
        -
            name: file
            label: 'Choose file'
            type: file
            id: file_data
            accept:
                - image
                - pdf
    buttons:
        -
            type: submit
            value: Submit
        -
            type: reset
            value: Reset
    process:
        -
            email:
                from: '{{ config.plugins.email.from }}'
                to:
                    - '{{ config.plugins.email.to }}'
                subject: '[ Aloola job request ] {{ form.value.name|e }}'
                body: '{% include ''forms/data.html.twig'' %}'
                attachments:
                    - file
        -
            save:
                fileprefix: feedback-
                dateformat: Ymd-His-u
                extension: txt
                body: '{% include ''forms/data.txt.twig'' %}'
        -
            message: 'Thank you for your Job request!'

**Comment by rhukster** [comment]
Please format your YAML properly in a code block and i'll take a look.
