### ISSUE TITLE
fileupload and dropzone seems to behave strangely and automatically sending emails when deleting uploaded files from the form

### ISSUE THREAD

**Issue by JohnMica** [getgrav/grav-plugin-email#136]
the issue seems to be related to both dropzone and how the file attachment is working.
### what happens / config
- static paths for all forms
- fresh download Admin + Grav (stable release and Quark default theme)
- create a page folder with the following structure

![image](https://user-images.githubusercontent.com/7076631/86235191-f4ccc780-bb8f-11ea-8347-43e0720aecc2.png)

- the test page has the following content [as per he AJAX form submission documentation](https://learn.getgrav.org/16/forms/forms/how-to-ajax-submission)
```
---
title: 'Ajax Test-Form'
form:
  name: ajax-test-form
  action: '/forms/test'
  template: form-messages
  refresh_prevention: true
  fields:
    name:
      label: 'Your Name'
      type: text
    upload_file:
      label: 'file Upload'
      type: file
      multiple: false
      limit: 1
      destination: user/data/files
      accept:
        - '.json'
    email:
      label: 'Your Email'
      type: email
  buttons:
    submit:
      type: submit
      value: Submit
  process:
    save:
      fileprefix: upload-
      dateformat: Ymd-His-u
      extension: txt
      body: "{% include 'forms/data.txt.twig' %}"
      attachments:
        - upload_file
    email:
      from: '{{ config.plugins.email.from }}'
      to: '{{ config.plugins.email.to }}'
    message: 'Thank you for your submission!'
---

<div id="form-result"></div>
<script>
$(document).ready(function(){
    var form = $('#ajax-test-form');
    form.submit(function(e) {
        e.preventDefault();
        $.ajax({
            url: form.attr('action'),
            type: form.attr('method'),
            dataType: 'html',
            data: form.serialize(),
            success: function(result) {
                $('#form-result').html(result);
            }
        });
    });
});
</script>
```
### what happens

- fill in the form input fields with name and email
- upload a `.json` file and it errors out when uploading the file

<img width="1710" alt="Captură de ecran din 2020-07-01 la 12 01 35" src="https://user-images.githubusercontent.com/7076631/86236982-d7e5c380-bb92-11ea-9b9b-10e0a92eaa9b.png">

- delete the uploaded file and the form sends 2 emails automatically with no 'SUBMIT' button clicking

<img width="2832" alt="Captură de ecran din 2020-07-01 la 12 01 59" src="https://user-images.githubusercontent.com/7076631/86237002-e03dfe80-bb92-11ea-81b7-bb133a4289c6.png">

- trying to send the form with the new uploaded file errors since the form has already been POSTed

<img width="1975" alt="Captură de ecran din 2020-07-01 la 12 02 32" src="https://user-images.githubusercontent.com/7076631/86237019-e92ed000-bb92-11ea-9b71-1f49b0147bf6.png">

and here is clip of what is going on to simplify even more the explanation
( since github wont allow mp4 inline upload i made it a zip )

[email file upload error.mp4.zip](https://github.com/getgrav/grav-plugin-email/files/4857388/email.file.upload.error.mp4.zip)

I wonder what am i doing wrong here or if there is an issue with the way file uploads are working in this latest versions (it used to work properly in older versions of Grav v1.6.0-rc.4 - Admin v1.9.0-rc.4 )

**Comment by mahagr** [comment]
Which Grav and admin verstions are you in now?

**Comment by JohnMica** [comment]
I’m testing with latest stable version downloaded yesterday from the website. Grav 1.6.26 and Admin 1.9.15. Email 3.0.9 Form 4.0.10

Regards,

John Mica

**Comment by rhukster** [comment]
Cleaning up old emails.  please read: https://getgrav.org/blog/new-email-plugin
