### ISSUE TITLE
Double opt-in

### ISSUE THREAD

**Issue by funktionaer** [getgrav/grav-plugin-email#143]
Hi everyone,
I use the email plugin with a contact form. Is it possible to generate a link in first place to confirm the email address and send and store the original mail just if the address is confirmed? Hope it is clear what I meant.

Cheers,
funktionaer

**Comment by mahagr** [comment]
It is a bit more involved as it needs quite some logic to work. Right now nobody has written anything like this, so the short answer is no, unless you are prepared to implement it yourself.

**Comment by rhukster** [comment]
Double-opt in should be used for mailing list signups (Mailchimp, etc)  not transactional one-time emails that the Email plugin generally deals with.
