### ISSUE TITLE
URGENT : Email/Form blocked by server

### ISSUE THREAD

**Issue by prinla** [getgrav/grav-plugin-email#153]
Changing to 20i.com as hosting company revealed a bigger problem in the email/form plugin:
![Screenshot 2021-06-07 183107](https://user-images.githubusercontent.com/16805582/121056741-cfdccd80-c7be-11eb-8816-cdcd33dcbbdf.jpg)
The problem was that no matter what way of configuring the email-plugin, the mail was not sent through to the receiver though it showed a succesful sending on the website and saved the email in the data manager.
The company 20i.com located that cause as you can see in the attached screen-shot from the support-team.
Any solutions to solve this problem?

**Comment by prinla** [comment]
The problem is an issue on two websites:
www.tiptopmallorca.com
www.sunprotection.es

**Comment by prinla** [comment]
20i.com offered assistance on this problem... The Customer Service Manager Austin Beresford knows about the issue and can be contacted on AB@20i.com

**Comment by rhukster** [comment]
BTW, this is not really a problem with the plugin, but more about configuration.  With grav you can set the 'from' address to anything, and simply set the 'reply to' address to the submitter of the form.  This way the 'from' is going to be an authorized user in the domain, but when you get the email and click "reply" you will send that response to the form author.

**Comment by rhukster** [comment]
BTW, please don't remove original comments. it makes it very confusing when going back over these issues.
