### ISSUE TITLE
Example with "steve@apple.com" is not a good one

### ISSUE THREAD

**Issue by spiro-trikaliotis** [getgrav/grav-plugin-email#155]
While I installed the plugin and tested it according to the documentation, I copy-and-pasted the line (as written in the documentation https://github.com/getgrav/grav-plugin-email#user-content-testing-with-cli-command):

    $ bin/plugin email test-email -t steve@apple.com

Before I was able to modify the recipient to something more sensible, I accidentially pressed ENTER.

The result was that SpamCop complained at my mail provider. In consequence, he asked me about this "illegal" mail.

I had to explain to him that this was not some malware or illegal use of my account to sent spam, but an accident in following your documentation. Fortunately, the support understood immediately and did not perform any actions on my side.

Thus, my suggestion: Use another mail address (for example, steve "at" example.com) so other people will not have the same problem by pressing ENTER too fast.

**Comment by m-schmale** [comment]
Funny, I did the same thing today. :laughing:

**Comment by spiro-trikaliotis** [comment]
Are you sure it is completed? On https://github.com/getgrav/grav-plugin-email#user-content-testing-with-cli-command, there is still the steve@apple.com mail address.

**Comment by rhukster** [comment]
https://github.com/getgrav/grav-plugin-email/tree/feature/symfony-mailer

in this branch (which is released as 4.0.0-rc.1)
