### ISSUE TITLE
sending email with an attachement

### ISSUE THREAD

**Issue by Artisy** [getgrav/grav-plugin-email#16]
it is not yet possible to send an email with an attachement. would be a nice feature ;-)

**Comment by flaviocopes** [comment]
The Email plugin is capable of handling attachments. What we miss is the logic of the integration with the Form plugin, to send uploaded files as attachments.

**Comment by muuvmuuv** [comment]
Would be nice too if I can say the file will be deleted and not saved after attaching it.

**Comment by flaviocopes** [comment]
Added to develop: https://github.com/getgrav/grav-plugin-email#sending-attachments-not-yet-released 

Nice if you can test it. 

Deleting a file is not a job of the email plugin, and actually I'm not sure the email plugin can send a file as attachment if it's not stored. So best option would be to setup a folder you purge periodically via cron job where you store the files.
