### ISSUE TITLE
Verification of To and From email in the plugins's settings

### ISSUE THREAD

**Issue by goshevs** [getgrav/grav-plugin-email#163]
Hi,

Any chance the verification of To and From email fields in the plugin's setting could be made optional? I am running an instance of grav in a docker container on my own server and all I need is to point to the docker bridge interface address so that I can receive an email from a form on the website onto the host. Currently, the verification does not allow me to specify anything such as user@localhost, user@sometherhost or user@10.0.0.2.

Thank you!

**Comment by rhukster** [comment]
This should not be a problem with Email 4.0 (currently in 4.0.0-rc.1 testing release)
