### ISSUE TITLE
Can't change/save SMTP configuration

### ISSUE THREAD

**Issue by zachmonkey** [getgrav/grav-plugin-email#164]
Not possible to change 

SMTP server
SMTP port
SMTP login name
SMTP password
SMTP auth mode

via admin interface admin/plugins/email

UI says "saved successfully" but changes are not kept. When leaving the page after saving this pop-up appears.

![image](https://user-images.githubusercontent.com/64352807/174221132-6899650f-d2f5-4d9e-afda-0ba9ad833015.png)

**Comment by rhukster** [comment]
I can't replicate this with a vanilla installation (grav + admin + form + login + email).  I suspect its a plugin that is causing this. What plugins do you have installed?

**Comment by zachmonkey** [comment]
@rhukster 

![image](https://user-images.githubusercontent.com/64352807/174227153-2b265cc2-a565-4f72-8131-5cff5ee9324d.png)
 
Ceevee theme

**Comment by rhukster** [comment]
<img width="335" alt="CleanShot 2022-06-16 at 22 54 55@2x" src="https://user-images.githubusercontent.com/1084697/174227727-60204661-8689-4a65-89b7-b61a31b03a9a.png">

Still no issues for me. 

Can you save other pages/plugins etc?

**Comment by zachmonkey** [comment]
Yep, this is the only plugin that refuses to save changes in this installation. I checked the raw yaml file out of frustration and the weird thing is if I change the settings in there, those new settings aren't reflected in the admin UI.

**Comment by rhukster** [comment]
can you provide the yaml config file so i can check for anomalies?

**Comment by zachmonkey** [comment]
Sure, see below. But the problem occurred before any direct alterations of the yaml file. I was able to save a config change once using the UI, then any subsequent changes were met with "saved successfully" followed by the warning popup "changes not saved" upon leaving the page. At this point I went for the yaml file. So this file shouldn't be the problem, despite its perhaps diabolical current state. Changed the values to "xx". 

`enabled: true
from: 'xx'
from_name: 'xx'
to: 'xx'
to_name: 'xx'
queue:
  enabled: false
  flush_frequency: '* * * * *'
  flush_msg_limit: 10
  flush_time_limit: 100
mailer:
  engine: 
  smtp:
    server: 'smtp.gmail.com'
    port: '587'
    encryption: 'TLS'
    user: 'xx'
    password: 'xx'
#    auth_mode: ''
#  sendmail:
#   bin: '/usr/sbin/sendmail -bs'
content_type: text/html
debug: false`

**Comment by rhukster** [comment]
Do you have any environment-based configurations?  You might be saving to a different location, eg `user/localhost/config/plugins/email.yaml`

**Comment by zachmonkey** [comment]
We've made no custom configurations whatsoever. Thing is installed out of the box, using the ceevee skeleton. Problem occurred upon the 2nd time changing the email plugin settings. Host is Hostinger, Litespeed server. "Problems plugin" shows no problems. Really feels like a bug, since the first save went through, but the second one and any subsequent ones didn't.

**Comment by rhukster** [comment]
It might be an issue with litespeed server.  We've not had any issues reported regarding this before. I still can't replicate your issue, so just trying to work out what's unique to you.  I'll see if i can test litespeed today.

**Comment by rhukster** [comment]
Nope, just fired up a new Linode and setup Litespeed via RunCloud and things just work fine.  No problem editing and saving the email config via the admin.

**Comment by zachmonkey** [comment]
All of a sudden it just started working... No changes by us, just time passing. I guess it could be an environment problem...
