### ISSUE TITLE
mb_strpos() expects parameter 1 to be string, array given with test version v4.0.0-rc.3

### ISSUE THREAD

**Issue by Andy-Flack** [getgrav/grav-plugin-email#167]
had a form with an email process
    process:
        -
            email:
                from: '{{ config.plugins.email.from }}'
                to:
                    - '{{ config.plugins.email.to }}'
                    - '{{ form.value.email }}'
  
That gives the error in the title
falling back to 
    process:
        -
            email:
                from: '{{ config.plugins.email.from }}'
                to: '{{ form.value.email }}'
works
(interim of one address in the array also fails)

This is new problem with the TEST version v4.0.0-rc.3 not with the 'live' version (thankfully).

**Comment by fugo** [comment]
I get this with any form I have on different website with email v4
First tought it was a form issue

**Comment by rhukster** [comment]
PHP Version?

**Comment by fugo** [comment]
Sorry, I forget this
PHP 8.1
