### ISSUE TITLE
File Attachments in Version 4.0 onward

### ISSUE THREAD

**Issue by jcpwdev** [getgrav/grav-plugin-email#174]
Hi there,

I was using the now deprecated `attachement()` method and functionality of the 3.x versions.

For now i failed to figure out how to do it in 4.0. Any hint would be greatly appreciated! Symfony Mailer has the `addPart()` Stuff, but if i am not mistaken this not exposed via the E-Mail-Plugin?

Best! Jo

**Comment by jcpwdev** [comment]
Hi Andy, thanks a ton for pointing me in the right direction! Consider this issue `done` :)

**Comment by rhukster** [comment]
np.
