### ISSUE TITLE
Server Error after update

### ISSUE THREAD

**Issue by lpbellerose** [getgrav/grav-plugin-email#179]
Hi, I'm having a server error after updating to the latest version of mail and trying to switch to sendmail config, but it works fine on version 3.2.0 (version I had for my local dev).

Here is the error :
![image](https://github.com/getgrav/grav-plugin-email/assets/29603484/7dd27649-cc15-40eb-ae13-59f291043e98)

Here is the log : 
`grav.CRITICAL: Unsupported sendmail command flags "/usr/sbin/sendmail"; must be one of "-bs" or "-t" but can include additional flags. - Trace: #0 /home/belleros/public_html/user/plugins/email/vendor/symfony/mailer/Transport/SendmailTransportFactory.php(24): Symfony\Component\Mailer\Transport\SendmailTransport->__construct() #1 /home/belleros/public_html/user/plugins/email/vendor/symfony/mailer/Transport.php(172): Symfony\Component\Mailer\Transport\SendmailTransportFactory->create() #2 /home/belleros/public_html/user/plugins/email/vendor/symfony/mailer/Transport.php(161): Symfony\Component\Mailer\Transport->fromDsnObject() #3 /home/belleros/public_html/user/plugins/email/vendor/symfony/mailer/Transport.php(113): Symfony\Component\Mailer\Transport->parseDsn() #4 /home/belleros/public_html/user/plugins/email/vendor/symfony/mailer/Transport.php(74): Symfony\Component\Mailer\Transport->fromString() #5 /home/belleros/public_html/user/plugins/email/classes/Email.php(450): Symfony\Component\Mailer\Transport::fromDsn() #6 /home/belleros/public_html/user/plugins/email/classes/Email.php(324): Grav\Plugin\Email\Email::getTransport() #7 /home/belleros/public_html/user/plugins/email/classes/Email.php(36): Grav\Plugin\Email\Email->initMailer() #8 /home/belleros/public_html/user/plugins/email/email.php(46): Grav\Plugin\Email\Email->__construct() #9 /home/belleros/public_html/vendor/symfony/event-dispatcher/EventDispatcher.php(264): Grav\Plugin\EmailPlugin->onPluginsInitialized() #10 /home/belleros/public_html/vendor/symfony/event-dispatcher/EventDispatcher.php(239): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch() #11 /home/belleros/public_html/vendor/symfony/event-dispatcher/EventDispatcher.php(73): Symfony\Component\EventDispatcher\EventDispatcher->callListeners() #12 /home/belleros/public_html/system/src/Grav/Common/Grav.php(597): Symfony\Component\EventDispatcher\EventDispatcher->dispatch() #13 /home/belleros/public_html/system/src/Grav/Common/Processors/PluginsProcessor.php(36): Grav\Common\Grav->fireEvent() #14 /home/belleros/public_html/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(50): Grav\Common\Processors\PluginsProcessor->process() #15 /home/belleros/public_html/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(62): Grav\Framework\RequestHandler\RequestHandler->handle() #16 /home/belleros/public_html/system/src/Grav/Common/Processors/InitializeProcessor.php(130): Grav\Framework\RequestHandler\RequestHandler->handle() #17 /home/belleros/public_html/system/src/Grav/Common/Debugger.php(546): Grav\Common\Processors\InitializeProcessor::Grav\Common\Processors\{closure}() #18 /home/belleros/public_html/system/src/Grav/Common/Processors/InitializeProcessor.php(131): Grav\Common\Debugger->profile() #19 /home/belleros/public_html/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(50): Grav\Common\Processors\InitializeProcessor->process() #20 /home/belleros/public_html/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(62): Grav\Framework\RequestHandler\RequestHandler->handle() #21 /home/belleros/public_html/system/src/Grav/Framework/RequestHandler/Middlewares/MultipartRequestSupport.php(40): Grav\Framework\RequestHandler\RequestHandler->handle() #22 /home/belleros/public_html/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(50): Grav\Framework\RequestHandler\Middlewares\MultipartRequestSupport->process() #23 /home/belleros/public_html/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(62): Grav\Framework\RequestHandler\RequestHandler->handle() #24 /home/belleros/public_html/system/src/Grav/Common/Grav.php(312): Grav\Framework\RequestHandler\RequestHandler->handle() #25 /home/belleros/public_html/index.php(47): Grav\Common\Grav->process() #26 {main} [] []`

The email.yaml is currently stock, but even if I change to smtp, the error continues. here is the sendmail yaml:
`
enabled: true
from:
from_name:
to:
to_name:
queue:
  enabled: false
  flush_frequency: '* * * * *'
  flush_msg_limit: 10
  flush_time_limit: 100
mailer:
  engine: sendmail
  smtp:
    server: localhost
    port: 25
    encryption: none
    user: ''
    password: ''
    auth_mode: ''
  sendmail:
    bin: '/usr/sbin/sendmail -bs'
content_type: text/html
debug: false
`

I can't install email without the site showing up this error. I'm I doing something wrong?

**Comment by rhukster** [comment]
What does your user/config/plugins/email.yaml look like?

**Comment by rhukster** [comment]
Also are you sure you don't have an environment based config? Search for email.yaml in your grav site and see if you have any others.

**Comment by lpbellerose** [comment]
Thanks @rhukster, found the email.yaml in the user/config/plugins/ folder and the -bs wasn't there. I thought configuration was only done in the user/plugin/email folder. My inexperience shows :) 

Thanks again!

**Comment by lpbellerose** [comment]
Thanks @rhukster, found the email.yaml in the user/config/plugins/ folder and the -bs wasn't there. I thought configuration was only done in the user/plugin/email folder. My inexperience shows :) 

Thanks again!
