### ISSUE TITLE
Smtp password visible

### ISSUE THREAD

**Issue by AustinEast** [getgrav/grav-plugin-email#18]
When inputting the Smtp password, I noticed that it doesn't hide it. Is this by design?
It doesn't feel all that safe to just have it in the open.

**Comment by flaviocopes** [comment]
I changed the field type to be 'password' but that's just a visualization thing.

If one gets access to the file containing the password your server is already compromised. Same thing as other CMS storing the mysql/smtp password in the configuration files (coming to my mind: WP, Drupal, Joomla).

You could move your user/ folder outside the webroot (more details coming soon in the docs) and we could come up with a better way to automatically encrypt/decrypt such value.

**Comment by AustinEast** [comment]
Sounds good. You make a good point!
