### ISSUE TITLE
Email sent to default "From"  ignores default "to" 

### ISSUE THREAD

**Issue by petrus9** [getgrav/grav-plugin-email#182]
When I set a default "From" and "To"  email addresses,   The "to" email address is ignored and email is only sent to the "From" address from the "From" address.  

Expected:   Email is sent to the "To address"  from the "From"  address. 
![Plugin-Email-Big-Picture](https://github.com/getgrav/grav-plugin-email/assets/63444532/1e30221e-9b2f-4446-8f02-3a6a26d7919b)

**Comment by rhukster** [comment]
How are you sending the email? Is this a form in your site? If so, can you provide the form definition via the page's .md file?

**Comment by petrus9** [comment]
Actually,  you can set this as resolved, the form markdown had  "default from"  in both the from and to fields!  Thanks!
