### ISSUE TITLE
TTL isn't a valid Encryption Stream

### ISSUE THREAD

**Issue by raphael-riel** [getgrav/grav-plugin-email#20]
Did you mean "tls" ?
https://github.com/getgrav/grav-plugin-email/blob/master/blueprints.yaml#L100

**Comment by rhukster** [comment]
Yup, looks like a typo!

**Comment by raphael-riel** [comment]
@rhukster : "TTS" for the label isn't much better :smile:

**Comment by rhukster** [comment]
Ugg.. this is what you get when you do stuff still half asleep!

**Comment by rhukster** [comment]
FYI, probably safer for everyone if next time you just edit the file and it will create a PR i can merge :)

**Comment by raphael-riel** [comment]
Will do. Thanks!
