### ISSUE TITLE
Asking, which's faster

### ISSUE THREAD

**Issue by benyaminl** [getgrav/grav-plugin-email#30]
I see that there's some option to sent mail, but for me now it's only working through the smtp. Nah the thing that I wanted to ask, which's faster from 3 option available for grav? SMTP, PhpMail or SendMail?

**Comment by flaviocopes** [comment]
On most servers PHP mail() won't work as it's marked as spam even before reaching the destination inbox. Same for sendmail. Just search why on Google. The safest way is almost always use a SMTP server. I have this experience from all the major PHP CMS out there.

That said, which is faster is a combination of factors and you need to do your testing in your setup. With SMTP as you're delegating the email sending to another server, you offload that task, but in turn you do a network connection to another server.
