### ISSUE TITLE
Cannot enter multiple To: addresses in Admin

### ISSUE THREAD

**Issue by blizam** [getgrav/grav-plugin-email#31]
Admin plugin > Email to: field

if you try and specify: mail@example.com, mail+1@example.com, mail+2@example.com

You get an error... Tooltip says:

A part following '@' should not contain a symbol ',' .

And it won't allow you to save...

you can edit the email.yaml files as such:

```
to:
  - mail@example.com
  - mail+1@example.com
  - mail+2@example.com
```

and it works fine... and generates the same comma delimited values I listed above in the Email Admin

**Comment by w00fz** [comment]
That's because the field is of type `email` but it's missing the `multiple="multiple"` attribute. The `multiple` attribute will fix the validation issue but I don't think multiple emails are supported in the email plugin itself, needs to be looked at.

**Comment by blizam** [comment]
https://github.com/getgrav/grav-plugin-email/blob/master/README.md#multiple-email-address-strings

It works by editing the email.yaml in user/config/plugins/  -- which will then show mulitple email addresses in the Email Admin... you just can't do it in via the Admin because of that validation

**Comment by w00fz** [comment]
Yes, that's correct, you can use it, manually.

What I'm saying is that the validation in Grav Core and the yaml field for the `to` recipient in the email plugin, do not support multiple addresses.

**Comment by w00fz** [comment]
This is now fixed with https://github.com/getgrav/grav/commit/3529d19c8f30ff20136b86066e95398b9bac6199 . 
The email plugin also now allows a multiple attribute, as per [w3c specs](https://www.w3.org/TR/html-markup/input.email.html#input.attrs.multiple)
