### ISSUE TITLE
Need a test button

### ISSUE THREAD

**Issue by astfgl** [getgrav/grav-plugin-email#32]
Can you please add a "Test" button on the configuration page, which causes a simple test email to be sent with the current configuration settings. Any errors generated before the email has been successfully sent to the first mail handler should be displayed.

The button should perform simple sanity checks on the current configuration before attempting to send the email and issue a warning, for example, if SMTP has been selected but there is no SMTP server specified.

To look cool, the button could change to "Save and Test" if there are unsaved changes on the page.

Regards, Glen.

**Comment by rhukster** [comment]
There is a test CLI command, this is better as it gives feedback and dumps out the current configuration.
