### ISSUE TITLE
email plugin doesn´t work with ssl / tls

### ISSUE THREAD

**Issue by gewerbeschule** [getgrav/grav-plugin-email#33]
**_When I test the plugin with mailtrap.io everything works fine.
The configuration in user/config/plugin/email.yaml ist as follows:_**

```
enabled: true
from: my@domain.de
to: my@domain.de
mailer:
  engine: smtp
  smtp:
    server: mailtrap.io
    port: 2525
   # encryption: 
    user: 123546
    password: 	12345
  sendmail:
    bin: /usr/sbin/sendmail
content_type: text/html
debug: true
```

**_When I change the configuration to:_**

```
enabled: true
from: xxx@yyy-bergedorf.de
to: xxx@yyyy-bergedorf.de
mailer:
  engine: smtp
  smtp:
    server: smtp.1und1.de
    port: 465
    encryption: ssl
    user: xxx@yyy-bergedorf.de
    password: abcdefg
  sendmail:
    bin: /usr/sbin/sendmail
content_type: text/html
debug: true
```

**_I get the following error:_**
0 - Connection could not be established with host smtp.1und1.de [Connection timed out #110] Log data: ++ Starting Swift_SmtpTransport !! Connection could not be established with host smtp.1und1.de [Connection timed out #110] (code: 0)

**_I tested all combinations of ports and encryptions and also with gmail smtp-server. Any help is appreciated._**

**Comment by flaviocopes** [comment]
Are you sending emails from localhost?

**Comment by flaviocopes** [comment]
If so, Swiftmailer (user by this plugin) does not support self-signed certificates yet: https://github.com/swiftmailer/swiftmailer/issues/571


Related: https://github.com/getgrav/grav-plugin-email/issues/23

**Comment by gewerbeschule** [comment]
I am sending the emails from my Webhosting. server 1and1. So it is not from localhost. Thanks for your help.

**Comment by flaviocopes** [comment]
With mailtrap the same configuration works fine, but as soon as you switch smtp server it does not work any more?

**Comment by gewerbeschule** [comment]
Yes it is like this. Can I post a log or do you have another sample configuration which works fine?

**Comment by flaviocopes** [comment]
No actually I don't have an exact answer for this. It works with one, so it should work with the others too, unless it's some underlying problem with the SSL certificate that prevents it to talk correctly to the live SMTP server

**Comment by gewerbeschule** [comment]
How can I check this with the ssl certificate? Really thanks for your help.

**Comment by gewerbeschule** [comment]
Hello Flavio,

I solved the problem. I changed the engine from "smtp" to "mail" and 
everything worked fine.

Thank you again very much for your help.

I have got another question about your fantastic theme sora. I am using 
it for our sabbatical and I don´t want the email-field in the footer 
(bottom of the homepage).

Can you tell me, how to get rid of it?

Does the Grav-Team has got a Paypal account?


Yours sincerely.

Yours sincerely

Thomas Grimm



Am 18.07.2016 um 19:03 schrieb Flavio Copes:

**Comment by gewerbeschule** [comment]
Solution for the problem: Change the engine in email.yaml from "smtp" to "mail" and it works fine.

**Comment by flaviocopes** [comment]
By setting "mail" you're using the PHP mail() functionality, not using the SMTP email sending - might work just fine in your case (on some servers it does not work), just be aware that it's not using your SMTP server.

**Comment by chrisallick** [comment]
> If so, Swiftmailer (user by this plugin) does not support self-signed certificates yet: [swiftmailer/swiftmailer#571](https://github.com/swiftmailer/swiftmailer/issues/571)
> 
> Related: #23

Any work around for this? I'm on a mac using mailtrap smtp. Was hoping to test before I resort to testing on production.
