### ISSUE TITLE
Update swiftmailer to 5.4.3

### ISSUE THREAD

**Issue by Pls** [getgrav/grav-plugin-email#37]
> E_WARNING - getmypid() has been disabled for security reasons

Getting this warning right now because 5.4.2 version has this function included. Latest version doesn't have it.

Let's update to 5.4.3 version. Cheers :)

**Comment by rhukster** [comment]
https://github.com/getgrav/grav-plugin-email/commit/c9d7005db379804adeed9915c22531bcc0a03387

Done and released for next GPM update (20 mins)

**Comment by Pls** [comment]
Cheers!

**Comment by yaazkal** [comment]
Hi, I have latest verion of the mail plugin and I can see that it has swiftmailer 5.4.3, but this version also has a call to that `getmypid()` function at `lib/classes/Swift/Mime/SimpleMimeEntity.php` line 83. So I'm getting a Grav error

`Whoops\Exception\ErrorException thrown with message "getmypid() has been disabled for security reasons"`

Any fix to that? Do I need to allow that function on the server?

**Comment by Pls** [comment]
As a workaround for now I replaced all getmypid() function calls with uniqid() calls. That works for me.

**Comment by flaviocopes** [comment]
Yes that must be enabled on the server, it's an upstream issue. @yaazkal commented in https://github.com/swiftmailer/swiftmailer/issues/745 👍  

We can't do anything on this side until they release an update with a fix for this.

**Comment by yaazkal** [comment]
Thanks @Pls I've replaced the other two references to that function and site is working now; I hope they will include a fix for the next version.

Regards.
