### ISSUE TITLE
is it possible to integrate ajax form submission on this plugin?

### ISSUE THREAD

**Issue by rlynjb** [getgrav/grav-plugin-email#42]
Hi, I am working on a form plugin. Im a newbie with php as well. I was wondering if we can hook an ajax script to avoid refreshing the page that contains contact form.
What I do so far is defined fields on a .md file but to avoid refreshing the page, Im planning on using ajax to send data to process hook.. is this possible?

Thank you

**Comment by flaviocopes** [comment]
It's surely possible. If you intercept the submit event on a form and submit it using AJAX it's going to be processed in the same way a "normal" submit event works. 

You then need to care about the return value and update the page accordingly.

**Comment by flaviocopes** [comment]
Closing as it's not really an issue of the email plugin

**Comment by rlynjb** [comment]
thank you @flaviocopes it works!! :-)
