### ISSUE TITLE
Email.php): failed to open stream: No such file or directory

### ISSUE THREAD

**Issue by ktaranov** [getgrav/grav-plugin-email#44]
Hi, guys.

Move mys site to vps hosting and get this error:

```
 Whoops \ Exception \ ErrorException (E_WARNING)
include(/var/www/taranov.pro/user/plugins/email/vendor/composer/../../classes/Email.php): failed to open stream: No such file or directory
```

Could you help me with this issue on http://taranov.pro/ ?

**Comment by flaviocopes** [comment]
Most probably the vendor/ folder is gitignored and is not copied to your server, can you check if this is the case?

**Comment by ktaranov** [comment]
@flaviocopes, thanks for reply. Solved this issue here https://github.com/getgrav/grav/issues/1143
