### ISSUE TITLE
class Email not found

### ISSUE THREAD

**Issue by cord** [getgrav/grav-plugin-email#47]
Hi guys,

after updating to the latest versions (core + plugins) grav stopped (local worked, but not on fortrabbit) with the error "class Email not found" in

`/plugins/email/email.php`

After re-adding the line

`require_once __DIR__ . '/classes/email.php';`

like it was in a previous version:

```
public function onPluginsInitialized()
    {
        require_once __DIR__ . '/classes/email.php';
        require_once __DIR__ . '/vendor/autoload.php';

        $this->email = new Email();

        if ($this->email->enabled()) {
            $this->grav['Email'] = $this->email;
        }
    }
```

the error was gone.

**Comment by cord** [comment]
fortrabbit support: their system is case sensitive, mac is not.
So I guess somewhere is a case typo?

**Comment by rhukster** [comment]
what version where you on before and what are you on now? I know we had that issue about a year ago, but we fixed it.

**Comment by cord** [comment]
I updated from

v2.3.0
04/20/2016

**Comment by rhukster** [comment]
try removing `user/plugins/email`folder, and reinstalling email plugin via gpm.

**Comment by cord** [comment]
that did the trick!
