### ISSUE TITLE
How to implement custom mail function?

### ISSUE THREAD

**Issue by kaladivo** [getgrav/grav-plugin-email#48]
I am pretty new to the grav. I like the CMS, it is great.

But one thing I am struggling with is that I need to implement custom mail function. I want to send mails using [sparkpost](https://www.sparkpost.com/). Is there any way how to implement custom mail engine? 

I know the answer will probably be trivial. But I can't find it anywhere...

**Comment by rhukster** [comment]
Sparkpost seems to use its own custom method. You could fork the email plugin and add support. Or create your own plugin, but that is less optimal.

**Comment by rhukster** [comment]
Actually Sparkpost now has SMTP support and I just tested and it works fine.  I've updated the README.md with an example of the setup.
