### ISSUE TITLE
delivery to domains ending different than .com not working

### ISSUE THREAD

**Issue by pzimbron** [getgrav/grav-plugin-email#52]
We tried to send a mail to domains ending in .mx and .us and is not working, it just works with .com

**Comment by rhukster** [comment]
Could you please send paste email.yaml configuration (minus any passwords).

**Comment by flaviocopes** [comment]
Also, did you configure the plugin to use a SMTP server, or are you relying on the PHP mail functionality, which is the default configuration?

**Comment by rhukster** [comment]
I've added a bunch more example services and options.  i've also tested these so i KNOW they work :) https://github.com/getgrav/grav-plugin-email/blob/develop/README.md
