### ISSUE TITLE
Using different to: and from: addresses

### ISSUE THREAD

**Issue by chortlemyballs** [getgrav/grav-plugin-email#56]
Using v2.6.0 when configuring the setting via the grav admin panels plugin page setting the from address seem to over ride the to address.

I.E. If I set the from field as no-reply@server.com and the to field as info@server.com when a message is sent via the contact form it will be sent to no-reply@server.com from no-reply@server.com. Rather than to info@server.com from no-reply@server.com.

**Comment by chortlemyballs** [comment]
Sorry was misconfigured file.

**Comment by rhukster** [comment]
Can't get past your username :)

**Comment by chortlemyballs** [comment]
Thanks mate, all the good names were taken.

This probably isn't the right place to ask but....

Any chance you'd point me in the right directions to get my contact form emails to convert to plain text when sending? If someone uses an apostrophe in the contact form I'm getting the entity number in the email. So I'm displays as I&#039;m?

**Comment by chortlemyballs** [comment]
Displays as `I&#039;m`
