### ISSUE TITLE
Form notices unreliable

### ISSUE THREAD

**Issue by sunyatasattva** [getgrav/grav-plugin-email#57]
I'm having a problem whereby the form confirmation messages gets shown unreliably. The email gets sent correctly, but the confirmation mostly doesn't show up in my production environment (and mostly does show up in my local dev environment). Sometimes the notice gets stuck no matter what and shows up even if I open an incognito window with the page.

How can I debug this issue?

**Comment by flaviocopes** [comment]
The email is sent, but it does not reach your inbox? Or you're talking about other notices? 

How is the email plugin configured, using SMTP or PHP mail?

**Comment by sunyatasattva** [comment]
Sorry for the lack of clarity. The email is sent and received. The notice I am talking about is the "Thank you" message on the site.

**Comment by flaviocopes** [comment]
Strange issue. Can you open it on the form plugin repo instead of this?

**Comment by sunyatasattva** [comment]
Thank you, I just did. We can close this here, then? Still, do you have suggestions on how could I debug the notice itself?
