### ISSUE TITLE
email plugin not sending email with error #110

### ISSUE THREAD

**Issue by domclassic** [getgrav/grav-plugin-email#64]
Hi,

I'm trying to use the plugin to send a test email to my mailtrap inbox. here is the config I enter in the admin panel:

Mail Engine: SMTP
SMTP server: smtp.mailtrap.io
Port: 465
encryption: None
login: 9e05ad03b3faa5 (I'm sure it is the right login)
password: xxxxxxxxxxx (I'm sure it is the right password)
debug enabled

here is the error I get:

0 - Connection could not be established with host smtp.mailtrap.io [Connection timed out #110] Log data: ++ Starting Swift_SmtpTransport !! Connection could not be established with host smtp.mailtrap.io [Connection timed out #110] (code: 0)

I am running on funio.com webhost
Any help will be appreciated. Thanks!

**Comment by rhukster** [comment]
It sounds like your hosting provider is perhaps blocking outbound connections to port 465? Either that or it simply cannot resolve `smtp.mailtrap.io` I would suggest trying to get to the terminal and pinging that host, or even telneting to port 465 on that host to see if you can reach it.  Also you could try contacting your hosting provider for their input.

**Comment by rhukster** [comment]
I've added a bunch more example services and options.  i've also tested these so i KNOW they work :) https://github.com/getgrav/grav-plugin-email/blob/develop/README.md

**Comment by rhukster** [comment]
Just double-checked and tested this, it works fine, so must be your config or account, please double check and reopen if this continues to be an issue.
