### ISSUE TITLE
Cannot send emails using smtp.gmail.com

### ISSUE THREAD

**Issue by alfre22** [getgrav/grav-plugin-email#65]
Hi, I'm trying to configure Gmail SMTP server to sending emails for a website developed on Grav CMS.

I set the email plugin configuration according to [documentation](https://github.com/getgrav/grav-plugin-email) and I use [a contact form](https://learn.getgrav.org/forms/forms/example-form) to receive feedback from my clients.

These are my settings (file /user/config/plugins/email.yaml):

```
enabled: true
from: myaccount@gmail.com
from_name: 'My Name'
to: myaccount@gmail.com
to_name: 'My Name'
mailer:
  engine: smtp
  smtp:
    server: smtp.gmail.com
    port: 587
    encryption: tls
    user: myaccount@gmail.com
    password: MyPassword
  sendmail:
    bin: /usr/sbin/sendmail
content_type: text/html
debug: false
```

I've activated IMAP service on my Gmail settings, allowed access for less secure apps and activated DisplayUnlockCaptcha on the account I'm using.

Everything seems working and I can send several emails for testing, but after a while emails are not sent anymore. I dont' know what is happening. Maybe Gmail is banning the system?

This site receives low traffic, I'm not expecting more than a couple emails per week.

Thanks in advance!

**Comment by rhukster** [comment]
Please test with the CLI command to make sure email is being sent properly. See the README.txt for details

**Comment by alfre22** [comment]
Another idea? I have no ssh access to my server because is not available for my hosting plan. :-/

**Comment by rhukster** [comment]
Ugg... Have you tried sending test messages with your form? Getting any visible errors?

**Comment by alfre22** [comment]
Yes, if I check the settings and save the configuration, whether using the admin plugin or FTP access to my hosting, everything works fine in the beginning, but after a few minutes stops working.

If I use mailtrap.io to track, I can read the emails. To check this out, I change this:

enabled: true
from: myaccount@gmail.com
from_name: 'My Name'
to: myaccount@gmail.com
to_name: 'My Name'
mailer:
  engine: smtp
  smtp:
    server: smtp.mailtrap.io
    port: 2525
    encryption: tls
    user: mailtrapusername
    password: mailtrappass
  sendmail:
    bin: /usr/sbin/sendmail
content_type: text/html
debug: false

**Comment by alfre22** [comment]
Right now I have mailtrap.io as server and is not working, but I can't find any log with info about what is happening.

**Comment by rhukster** [comment]
I've hooked in the `debug: true` option to use a new `logs/email.log` file that you can inspect for issues.  However for Gmail i've also added a new section to the README.txt:

### Google Email

A popular option for sending email is to simply use your Google Accounts SMTP server.  To set this up you will need to do 2 things first:

1. Enable IMAP in your Gmail `Settings` -> `Forwarding and POP/IMAP` -> `IMAP Access`
2. Enable `Less secure apps` in your [user account settings](https://myaccount.google.com/lesssecureapps)
3. If you have 2-factor authentication, you will need to create a unique application password to use rather than your personal password

Then configure the Email plugin:

```
mailer:
  engine: smtp
  smtp:
    server: smtp.gmail.com
    port: 465
    encryption: ssl
    user: 'YOUR_GOOGLE_EMAIL_ADDRESS'
    password: 'YOUR_GOOGLE_PASSWORD'
```

> NOTE: Check your email sending limits: https://support.google.com/a/answer/166852?hl=en

**Comment by rhukster** [comment]
for mailtrap there's an example in the README.txt also:

```
mailer:
  engine: smtp
  smtp:
    server: mailtrap.io
    port: 2525
    encryption: none
    user: YOUR_MAILTRAP_INBOX_USER
    password: YOUR_MAILTRAP_INBOX_PASSWORD
```

**Comment by rhukster** [comment]
I've added a bunch more example services and options.  i've also tested these so i KNOW they work :) https://github.com/getgrav/grav-plugin-email/blob/develop/README.md
