### ISSUE TITLE
Plugin event hook to alter email recipients depending on form values.

### ISSUE THREAD

**Issue by BootedWeb** [getgrav/grav-plugin-email#66]
I have a form which should be sent to different offices, depending on values within the form. The easiest way to do this without duplicating the existing plugin and hacking it, is adding an event hook before https://github.com/getgrav/grav-plugin-email/blob/6e24a6827d53ed0e299cb57ecbfcc9d27ba361bd/email.php#L75 and writing a plugin hooking in on that event, altering the parameters. onEmailSend, for example.

Could you add such an event hook? Or is there another way to achieve the functionality?

**Comment by rhukster** [comment]
Please submit a PR with the event hook in email plugin and i'll take a lookl

**Comment by rhukster** [comment]
Merged for next release!
