### ISSUE TITLE
mailer.engine vs. mailer.default

### ISSUE THREAD

**Issue by hctom** [getgrav/grav-plugin-email#7]
I just stumbled upon the following: In the blueprint there is ```mailer.engine``` defined as a hidden field (which of course results in no configuration options). On the other hand, there is ```mailer.default```, which allows configuration, because it is defined as a select field with options for
* ```none```
* ```mail```
* ```smtp```
* ```sendmail```

In the ```Email``` class then the ```plugins.email.mailer.engine``` config value is used to initialize the correct mailer (which was introduced in 89274e44c52344710fcd370e3394ea1fc635ef29). 

So now I am really confused if something got messed up here? Perhaps the maintainers can have a look at that or give me advice how this should be solved.

**Comment by hctom** [comment]
Any news on this? I think this should really be fixed soon, because the configuration option in the admin interface does not have any effect right now.

**Comment by rhukster** [comment]
I was kinda waiting for the dust to settle with all the PRs :) and comments.  Also @flaviocopes has been looking into this so figured I would leave this to him.

**Comment by hctom** [comment]
Okay no problem... and I promise, I will stop bothering when all the other stuff in the PRs is done ;)

**Comment by flaviocopes** [comment]
I checked the source. In the beginning it was using `mailer.default`, but now the plugin uses the setting from `mailer.engine`. So we should remove `default` and add the select options to `engine`. 

I didn't realize this because I almost always edit the `email.yaml` file directly, and there `default` does not exist.

**Comment by flaviocopes** [comment]
Since https://github.com/getgrav/grav-plugin-email/commit/8013dd249af996cdc63e4b8702f6efd179cff296

**Comment by rhukster** [comment]
Is this sorted now???

**Comment by hctom** [comment]
Give me half an hour ;)

**Comment by hctom** [comment]
See #12
