### ISSUE TITLE
Problem with Sendmail when using reCaptcha Contact plugin

### ISSUE THREAD

**Issue by gaasen** [getgrav/grav-plugin-email#76]
Hi there,
When upgrading the Email Plugin to the current version (that have removed the php mail option) I now get an error with the contact form provided through the reCaptcha Contact Plugin.

When submitting a contact form I get the following error:

Swift_TransportException
Unsupported sendmail command flags [/usr/sbin/sendmail]. Must be one of "-bs" or "-t" but can include additional flags.

Any ideas?

**Comment by rhukster** [comment]
You need to add these options to the `sendmail: bin:` config params for the plugin: https://github.com/getgrav/grav-plugin-email/blob/develop/email.yaml#L15

**Comment by gaasen** [comment]
hi there and thanks a lot for answering.
I have looked in my email.yaml and it looks like the one in your link.

I have not done any alterations of the email.yaml file. 
Should there be any changes to this?

My email.yaml file looks as follows:

enabled: true
from:
from_name:
to:
to_name:
mailer:
  engine: sendmail
  smtp:
    server: localhost
    port: 25
    encryption: none
    user: ''
    password: ''
  sendmail:
    bin: '/usr/sbin/sendmail -bs'
content_type: text/html
debug: false

**Comment by gaasen** [comment]
sorry, I just realised that I havent got Sendmail installed on my server, so it is my fault that it does not work for me.
