### ISSUE TITLE
Failed to authenticate on SMTP server with username 

### ISSUE THREAD

**Issue by bluis4** [getgrav/grav-plugin-email#78]
Hello,
Last night when i tried to send email using the contact form, everything was fine. But tonight when i tried to send an email for test, this error show up

```
Swift_TransportException 
Failed to authenticate on SMTP server with username "xxx@mydomain.com" using 2 possible authenticators
```

This is the setup for email.yaml file

```
enabled: true
from: xxx@mydomain.com
to: xxx@mydomain.com
to_name: 'My Name'
mailer:
  engine: smtp
  smtp:
    server: mail.mydomain.com
    port: 465
    encryption: ssl
    user: 'xxx@mydomain.com'
    password: 'xxxxx'
  sendmail:
    bin: '/usr/sbin/sendmail -bs'
content_type: text/html
debug: false
```

any help would be appreciate.

Regards,

Luke

**Comment by rhukster** [comment]
hmm.. i have no clue what that means.. maybe try searching on the swiftmailer issues list?

**Comment by rhukster** [comment]
It sounds like an upstream issue with your email provider.  Did you get it sorted?

**Comment by bluis4** [comment]
It's all good now. It was a connection issues from my hosting side

**Comment by Moonlight63** [comment]
What exactly was the connection issue? I'm having the same problem now...

**Comment by Sogl** [comment]
Same problem after update from 1.3.10 to 1.4.7 with all plugins
