### ISSUE TITLE
"The connection to the GPM cannot be established" after updating to 1.4.1

### ISSUE THREAD

**Issue by rolve** [getgrav/grav-plugin-email#84]
Hi,

I just updated Grav to 1.4.1 and now I get the "The connection to the GPM cannot be established" message in the Admin Panel. Obviously, this has nothing to do with OpenSSL or cURL missing, because Grav was able to update itself via the Admin Panel just before.

What could be the problem here? Unfortunately, I'm on a shared hosting, so I cannot use SSH...

**Comment by rhukster** [comment]
Why is this on email repo? Mistake?

**Comment by rolve** [comment]
Oh, yes, sorry. Can you move it or should I reopen it on the other side?
