### ISSUE TITLE
Sending mails when neither SMTP or Sendmail is available

### ISSUE THREAD

**Issue by grantbunyan** [getgrav/grav-plugin-email#86]
I've recently upgraded allthethings on a client's Grav install and discovered that sending via PHP Mail is now deprecated on the Grav side. This is a very big issue on 1&1 shared hosting packages which appears to have support for neither sendmail or outbound SMTP.

**Comment by rhukster** [comment]
Time for new hosting!

We use SwiftMailer which is the most popular SMTP package available for PHP.  The supported transports are not something we have direct control over.

Seriously though, you should be able to use an external SMTP server no matter the hosting provider, however, you might need to use SSL/TLS and a non-standard port.  Most of the email service providers support a variety of ports.
