### ISSUE TITLE
Avoid passwords in Git repos by using getenv

### ISSUE THREAD

**Issue by DCBT** [getgrav/grav-plugin-email#87]
I'm hosting in Heroku, direct from GitHub, and didn't want to expose my SendGrid API key in the repo.

I added a field in the blueprint to allow the user to enter the name of an environmental variable instead of a password:

```
    mailer.smtp.passwordenvvar:
      type: text
      size: medium
      label: Environmental Variable Name
```

And altered classes/Email.php to use the environmental variable value if the name was set:

   ```
              switch ($mailer) {
                case 'smtp':
                    $transport = \Swift_SmtpTransport::newInstance();

                    $options = $config->get('plugins.email.mailer.smtp');
                    if (!empty($options['server'])) {
                        $transport->setHost($options['server']);
                    }
                    if (!empty($options['port'])) {
                        $transport->setPort($options['port']);
                    }
                    if (!empty($options['encryption']) && $options['encryption'] != 'none') {
                        $transport->setEncryption($options['encryption']);
                    }
                    if (!empty($options['user'])) {
                        $transport->setUsername($options['user']);
                    }

                    if (!empty($options['passwordenvvar'])) {
                        $transport->setPassword(getenv($options['passwordenvvar']));
                    }
                    else if (!empty($options['password'])) {
                        Grav::instance()['log']->critical('password');
                        $transport->setPassword($options['password']);
                    }
                    break;
```

It's not perfect by any means, but it solved a problem I was having.

**Comment by rhukster** [comment]
I think this could be done...

**Comment by ghtmtt** [comment]
+1 I think that with the current configuration there could be really really easy that users will update the `user/plugin/config/email.yaml` with password and other sensible data. Is there any hashed password available? As for the admin plugin?

**Comment by torohill** [comment]
This issue is solved with the Dotenv plugin - https://github.com/Ralla/grav-plugin-dotenv/

**Comment by NicoHood** [comment]
I was also able to solve the issue with the dotenv plugin:
```
plugins.email.mailer.smtp.password='<password>'
```

I guess that is the best way to inject the password, isnt it @rhukster ?

**Comment by rhukster** [comment]
Environment variables are the 'safest' way to handle passwords such as these, but a lot of people simply don't have shell access and probably don't have the expertise to deal with environment variables.

I think the `dotenv` plugin solves the problem perfectly. I will probably use it myself 👍
