### ISSUE TITLE
Queues instead of immediate send

### ISSUE THREAD

**Issue by heihachi88** [getgrav/grav-plugin-email#89]
Would be good if you integrate mail queues that would run on a cron task instead of immediate sending. That's not convenient, because user has to wait 2-3 seconds before email is sent.

**Comment by rhukster** [comment]
With the jobs capability, we've added in the 1.6 beta release, this is now possible, so will look into a queue for a future version.

**Comment by rhukster** [comment]
https://github.com/getgrav/grav-plugin-email/commit/28ba458e7a10757e775cc389ff079c5404fcfeb8
This has been added in 3.0 branch!
