### ISSUE TITLE
Admin Plugin form should disable autocomplete

### ISSUE THREAD

**Issue by monkeyphysics** [getgrav/grav-plugin-email#90]
My config page keeps filling in and overwriting settings.
I see no reason to have autocomplete enabled on the settings page.

Please consider.

**Comment by rhukster** [comment]
Good call..

**Comment by rhukster** [comment]
I've added an `autocomplete="nope"` in version 3.0 branch.  That said, some browsers and password apps will ignore this standard attribute.  the 'nope' might help, but it's really all i can do.
