### ISSUE TITLE
Problem with Swift Mailer

### ISSUE THREAD

**Issue by PetrToman** [getgrav/grav-plugin-email#96]
Hello,
on many hostings, there is a problem with Swift Mailer - it calls ``proc_*`` functions which are disallowed and also, it does not support using PHP ``mail()`` function any longer.

I suggest switching to https://github.com/PHPMailer/PHPMailer.

**Comment by rhukster** [comment]
I evaluated PHPMailer and SwiftMailer when choosing an email library. SwiftMailer won hands down.  It's much better written, it's part of the Symfony ecosystem (and we use lots of Symfony libraries already), has a better license, and other reasons I forget!

**Comment by rhukster** [comment]
Good case in point. I just implemented mail queue support as that's something Swiftmailer can do, and with the scheduler in Grav 1.6, it makes a great solution. PHPMailer, not so much!
